cmd: "py.test --cov=simulate --cov-report=xml; ./coverage/2lcov.sed coverage.xml > coverage/lcov.info"
name: "py.test"
cwd: "{PROJECT_PATH}"
errorMatch:
    - "E\\s+(?<message>.*)\\n\\n(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):\\s+.+"
    - "(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):(.*\n([^\n]*\n)+E\\s+)(?<message>.*)"
