language: python

python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox-travis python-coveralls
script: 
  - tox
after_success:
  - coveralls

