language: python

# Can't use normal def, as no py37 yet
# python:
#   - 3.6
#   - 3.7

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox-travis python-coveralls
script: 
  - tox
after_success:
  - coveralls

