name: simulhave-dev
channels:
  - pyviz
  - bokeh
  - conda-forge
  - intel
  - defaults
  - numba

dependencies:
  - python=3.7
  - pandas=0.24
  - numpy=1.15
  - numba
  - icc_rt

  - pyviz
  - holoviews
  - panel
  - bokeh
  - python-graphviz

  - jupyterlab
  - pyviz_comms
  - nodejs
  # jupyter-labextension install @pyviz/jupyterlab_pyviz

  - pytest
  - pytest-watch
  - pytest-cov
  - pytest-runner
  - flake8
  - pylama
  - pylint
  - jedi
  - python-language-server
  - mypy
  - tox
  - twine
  - conda-build
