name: sim-dev
channels:
  - pyviz/label/dev
  - bokeh/label/dev
  - conda-forge
  - defaults
  - numba

dependencies:
  - python=3.7
  - pandas=0.24
  - numpy=1.15
  - numba
  - icc_rt

  - pyviz
  - holoviews
  - panel
  - bokeh
  - graphviz
  - python-graphviz

  - jupyterlab
  - pyviz_comms
  - nodejs
  - rise
  # jupyter-labextension install @pyviz/jupyterlab_pyviz

  - pytest
  - pytest-watch
  - pytest-cov
  - pytest-runner
  - flake8
  - pylama
  - pylint
  - jedi
  - python-language-server
  - mypy
  - tox
  - twine
  - conda-build
