name: simulhave
channels:
  - pyviz/label/dev
  - bokeh/label/dev
  - numba
  - pyviz
  - bokeh
  - conda-forge
  - defaults

dependencies:
  - pandas=0.23
  - numpy
  - numba
  - icc_rt

  - pyviz
  - holoviews
  - panel
  - bokeh
  - python-graphviz

