name: sim-prod
channels:
  - pyviz
  - bokeh
  - conda-forge
  - defaults
  - numba

dependencies:
  - python=3.7
  - pandas=0.24
  - numpy=1.15
  - numba
  - icc_rt

  - holoviews
  - panel
  - bokeh
  - python-graphviz

